#!/usr/bin/env python

deps = [
	'System.dll',
	'System.Core.dll',
	'nunit.framework.dll',
	'NLog.dll',
	'MPFuzz.Core.dll',
	'MPFuzz.Core.OS.Linux.dll',
]

bld(
	features = 'cs linux test',
	use = deps,
	source = bld.path.ant_glob('**/*.cs'),
	name = 'MPFuzz.Core.Test.OS.Linux.dll',
)
